Mpi omp support
hiker/fab_new pull request #14
Opened 2024-08-02 10:08 UTC by hiker

Adds support for specifying MPI and OpenMP in the config file.

2024-08-02 10:16 UTC, hiker commented
This patch is not 'as big' as it appears to be - because of adding parameters to BuildConfig, they had to be added to a lot of files and examples. Additionally, I addressed coding style issues as suggested by Matthew recently (max 80 characters/line). Note that the MPI based compiler classes are not proper wrapper yet, they will be re-implemented in the next PR.

2024-08-08 01:44 UTC, hiker commented
Quick explanation:
the idea of this PR is that the user defines in the BuildConfig if the build is to be done with MPI, and with OpenMP (they are not exclusive). This means that the ToolRepository can pick an appropriate compiler by default (if the user doesn't specify what compiler they want), which solves e.g. the problem that e.g. `ifort` is being picked as default for an intel-based build (instead of an Intel based MPI wrapper). ATM we hard-code this still in the script.
The support for OpenMP means that the compiler can select its own (compiler-specific) OpenMP flags. ATM we have these flags hard-coded in the scripts.

2024-08-12 05:21 UTC, lukehoffmann requested changes

2024-08-12 05:21 UTC, lukehoffmann commented on source/fab/build_config.py
> +    def mpi(self) -> bool:
Are these properties (`BuildConfig.mpi` and `BuildConfig.openmp`) used in you later tickets? Right now I can't see if they do anything. Couldn't I create a `BuildConfig(mpi=False)` and still use it with mpi?

2024-08-12 05:21 UTC, lukehoffmann commented on source/fab/tools/tool_repository.py
> +            self[category] = sorted(self[category],
Does this assume `add_tool` is never called after `set_default_compiler_suite`? That might be fine, I can't tell

2024-08-14 07:16 UTC, hiker commented on source/fab/tools/tool_box.py
>              return self._all_tools[category]
Yes. That feels questionable (and I would prefer to check that the tool has indeed the right MPI level), but the way LFRic builds were setup originally (not sure if this is still the case, since this changes from site to site) is that they actually compiler with a non-MPI compiler but provide include-flags (which is totally stupid, but it had some reason that I can't remember now). Now in order to ease the porting effort for other sites, I did not add a test. But I'll add a #TODO, so it can be added later if required.

2024-08-14 07:22 UTC, hiker commented on source/fab/tools/tool_box.py
> +        # from the ToolRepository, and at it, so we don't need to look
Indeed.

2024-08-14 07:25 UTC, hiker commented on source/fab/build_config.py
> +    def mpi(self) -> bool:
Good catch. MPI  was used in compile_c, but not compile_fortran (and as previously discussed, we don't raise an exception if you request MPI and a non-MPI compiler is already loaded, based on the idea that the user knows what they are doing). I am thinking more and more that we should raise an exception in this case :(
Openmp is used in both compile_c and ..._fortran

2024-08-14 11:17 UTC, hiker commented on source/fab/tools/tool_repository.py
> +            self[category] = sorted(self[category],
Not really. ATM I use this (in the NCI setup) to first pick our default suite (intel-classic), then add additional compilers (tau-wrapper around ifort) to the repository. This way the default will still remain the plain ifort (or mpi wrapper around ifort), while the tau ones (which are all of the same suite 'intel-classic') are available if a user wants to pick them, but they will not be picked by default.

Actually, now that I think about it, the order doesn't matter. Fab will first add the 'standard' compiler (e.g. ifort, mpif90-ifort), and whenever the default is changed, a stable-sort is called, so ifort/mpif90-ifort will be before any user added tool.

2024-08-14 13:39 UTC, hiker commented on source/fab/tools/compiler.py
> +                 openmp_flag: Optional[str] = None,
Good catch. I've fixed the order.

2024-08-14 13:39 UTC, hiker commented on tests/unit_tests/tools/test_compiler.py
> +                                                     '-o', 'a.o', ])
Yes, they are independent. And I have split the tests into smaller ones.

2024-08-14 13:40 UTC, hiker commented on tests/unit_tests/tools/test_compiler.py
I've parameterised all the valid compiler version tests to test both the compiler and mpi wrapper.

2024-08-14 13:40 UTC, hiker commented on tests/unit_tests/tools/test_tool_repository.py
> +    with pytest.raises(RuntimeError) as err:
Done.

2024-08-14 13:41 UTC, hiker commented on tests/unit_tests/tools/test_compiler.py
> +    with pytest.warns(UserWarning,
Done ... I think.

2024-08-14 13:50 UTC, hiker commented
I hope I've addressed all issues. Ready for next review.

2024-08-14 14:28 UTC, hiker commented on tests/unit_tests/tools/test_compiler.py
In hindsight a stupid idea of me. The next PR (compiler wrapper) refactors the MPI* wrapper and creates their own file with their own tests, so I had to remove the parameterisation in the next PR again. The 'future' compiler wrapper do explicitly test that the wrapper and the wrapper compiler report the same version :(

2024-08-16 05:22 UTC, lukehoffmann approved these changes

2024-08-16 05:25 UTC, merged