Compiler wrapper
hiker/fab_new pull request #16
Opened 2024-08-07 06:13 UTC by hiker

Adds proper compiler wrapper, which also fixes issues with old implementation of mpi.. wrapper.

2024-08-16 06:30 UTC, hiker commented
This adds CompilerWrapper implemented using a Decorator pattern (not in terms of Python decorators, just very explicit). It means esp. that wrapper like mpif90 and the 'wrapped' compiler now share compiler flags (so a site only needs to define compiler flags for say ifort, but can then use mpif90 as a wrapper around ifort to get the same flags).

2024-09-02 06:37 UTC, lukehoffmann requested changes
Sorry to take so long with this! I only found a few minor things to fix in the end

2024-09-04 04:44 UTC, hiker commented on Documentation/source/site-specific-config.rst
> +    :caption: Defning an mpicc compiler wrapper
Fixed.

2024-09-04 04:44 UTC, hiker commented on Documentation/source/site-specific-config.rst
> +to add a compiler wrapper as follows (example taking from the
Fixed.

2024-09-04 04:46 UTC, hiker commented on Documentation/source/site-specific-config.rst
> +and to the compiler wrapper - this will allow the wrapper and the
No, it's not checked, and I can't make up my mind if it should be checked or not ... maybe there are some use cases where you want a  'temporary' compiler that's not in the ToolRepository? I reworded this paragraph to indicate that it is recommended to add the wrapped compiler if you are defining a new one (plus a few other changes to be more precise).

2024-09-04 04:46 UTC, hiker commented on tests/unit_tests/tools/test_compiler_wrapper.py
> +    from the actual compiler.
You got me, I used C&P :)

2024-09-04 04:46 UTC, hiker commented on source/fab/tools/compiler.py
> +                 availablility_option: Optional[str] = None):
Wow - that's bad :) I've replaced this globally.

2024-09-04 04:47 UTC, hiker commented
Ready for next review.

2024-09-04 04:56 UTC, lukehoffmann commented on Documentation/source/site-specific-config.rst
> +and to the compiler wrapper - this will allow the wrapper and the
That looks good, thanks

2024-09-04 05:45 UTC, lukehoffmann requested changes

2024-09-04 05:45 UTC, lukehoffmann commented on source/fab/tools/compiler_wrapper.py
> +        return self._is_available
One more thing I noticed when looking ahead at the next change:

I think this should follow the pattern of other tools and override `check_available()`. It makes it easier if anyone should need to override this class in the future, and it makes it generally a bit easier to understand.

In that case we wouldn't need caching here because that is part of `is_available` in the base class.

2024-09-04 06:01 UTC, lukehoffmann commented on source/fab/tools/compiler_wrapper.py
> +        return self._compiler.category
Also, can we remove this, since we're already passing the category into the compiler?

The reason is because I want to add an optional category in the constructor and pass in `LINKER` when overriding it. I could do that as part of my change if it's easier

2024-09-04 13:56 UTC, hiker commented on source/fab/tools/compiler_wrapper.py
> +        return self._compiler.category
OK, I looked again, and I was wrong, it can indeed be safely removed, I totally forgot that CompilerWrapper inherits from Compiler.

2024-09-04 13:58 UTC, hiker commented on source/fab/tools/compiler_wrapper.py
> +        return self._is_available
Indeed - even more, since in case of compiler it all relies on get_version, I could just remove this function entirely, as far as I can see it works fine (is_available calls check_available in compiler, which calls get_version in compiler_wrapper, which handles wrapped compiler :) ).

Thanks

2024-09-04 23:54 UTC, lukehoffmann approved these changes
Thanks, I'm happy with this

2024-09-04 23:57 UTC, merged