Version tuples
hiker/fab_new pull request #18
Opened 2024-08-08 01:16 UTC by hiker

Just minor updates and simplification, so that this PR will be easier to get into the main repo.

2024-08-08 01:21 UTC, hiker commented
Hi Luke, the minor changes as discussed elsewhere.

2024-08-09 01:16 UTC, lukehoffmann requested changes
Thanks, mostly just some questions about the test

I've added some more thinking about inheritance style, but feel free to ignore that and we can move on

2024-08-09 01:16 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +                             version_output: str) -> str:
Now this has made me go down the same rabbit-hole again about how to do this inheritance 😊

Now my thoughts are:
* It feels wrong to me overriding a method when there's no explicit inheritance. That might just be my experience from other language, and maybe it's fine in Python? It does mean we have a `self` argument but we just ignore that and pass in the data that is part of `self` anyway.
* I feel like this stretches the idea of a 'mixin'. All the mixin examples I've seen only add completely new methods to a class, not overrides.
* Actually what we have is more like Diamond Inheritance, but not quite. If we made the inheritance explicit with `GnuVersionHandling(Compiler)` then it would literally be Diamond Inheritance (and we would be back to how it was in my first version 😂). I think that's more of an anti-pattern anyway.

So I personally think I like the style from before this change, where the concrete classes had the override methods and the mixins just provided a static method. 

I can also see the advantage of this being less code and still pretty easy to understand. I'll leave it to your judgement, since I'm still learning about classes and inheritance in Python.

2024-08-09 01:16 UTC, lukehoffmann commented on tests/unit_tests/tools/test_compiler.py
> +
You've got the same thing twice here. Is the first one meant to test `C_COMPILER?`

Also, could this be it's own test?

2024-08-09 01:16 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +            name = "ifort"
Thanks, this is actually much easier to read, because you don't have to think about where `name` might be coming from

2024-08-09 07:22 UTC, hiker commented on source/fab/tools/compiler.py
> +        exp = name + r" \(.*?\) ([\d\.]+)\b"
Yes, agreed. We actually had the problem that in the previous version the actual 'higher level test' (all parts are integer etc) were not used at all, since the regex caught the test cases.
My suggestion is that I add another test for these numbers (leading/training `.`) to make sure they fail as expected.

2024-08-09 07:33 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +        exp = name + r" \(.*?\) ([\d\.]+)\b"
Yes another test would make it clear

2024-08-09 07:53 UTC, hiker commented on source/fab/tools/compiler.py
> +                             version_output: str) -> str:
The main issue I had: without the declaration of the method in Compiler, mypy does complain, since it can't find the called method. And I prefer this solution over some kind of directive or so to disable this warning :( And I couldn't declare it static (since a static function cannot be overwritten, so I needed `self` in order to overwrite it).

2024-08-09 11:06 UTC, hiker commented on source/fab/tools/compiler.py
> +                             version_output: str) -> str:
In hindsight, we could have added a separate object that extracts the version number, and each compiler would have one of them. With a proper abstract baseclass, that would have worked. But that's now a lot of additional overhead :)

2024-08-12 00:05 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +        exp = name + r" \(.*?\) ([\d\.]+)\b"
Good work finding getting that regex worked out!

2024-08-12 00:07 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +                             version_output: str) -> str:
Yeah I don't want to make things any more complicated. I'm happy with the current solution

2024-08-12 00:09 UTC, lukehoffmann commented on tests/unit_tests/tools/test_compiler.py
> +
I realised this was probably duplicated during a merge, but I see you've fixed it now to test C and Fortran separately, which is good

2024-08-12 00:16 UTC, lukehoffmann reviewed
Sorry one last change. I was going to do it myself but I thought I'd better let you manage the branches

2024-08-12 00:16 UTC, lukehoffmann commented on tests/unit_tests/tools/test_compiler.py
> +    ifort = Ifort()
One final thing - this isn't testing the right thing because it's using an icc string in an ifort compiler. Can you either change the class or the string, so they're both icc or both ifort (and make sure the docstring matches) please?

2024-08-12 01:27 UTC, hiker commented on tests/unit_tests/tools/test_compiler.py
> +    ifort = Ifort()
Good catch.

2024-08-12 01:27 UTC, hiker commented
Thanks for checking. I've updated the test, good catch!

2024-08-12 01:30 UTC, lukehoffmann approved these changes
Thanks, looks good now

2024-08-12 04:04 UTC, merged