Handle compiler versions as integer tuples and verify compiler name
hiker/fab_new pull request #9
Opened 2024-07-23 01:18 UTC by lukehoffmann

Handles Issue #8 

When retrieving a compiler version, the compiler class will now:

 * check that the `--version` output contains a particular identifier for the expected compiler. By default this is `compiler.name`, but it can be overridden for each compiler with a new `version_token` argument in the constructor (required for `gfort` which outputs `GNU Fortran`)
 * return the components of the version as a tuple (previously a string)
 * raise an error for any unexpected formatting of the `--version` output (previously it would return an empty string in some cases)

2024-07-23 07:35 UTC, hiker requested changes
Good improvements. The usage of your `version_token` was a surprise (I expected the code to extraction version to be moved into the individual classes). Doing it this way means you need to consider output from more compilers to make sure they all work.

I have provided nvidia output as a comment, and will check the output for Cray compilers and provide them as additional comment later. But either verifying that your code design (one get_version to rule them all :) ) works is important, and if not, it might need some redesign.

2024-07-23 10:20 UTC, hiker commented
Here additional output for Cray compilers:
```
ftn -V
Cray Fortran : Version 8.7.0  Tue Jul 23, 2024  07:39:25

ftn -V
Cray Fortran : Version 8.5.7  Tue Jul 23, 2024  07:40:27

ftn -V
Cray Fortran : Version 15.0.1  Tue Jul 23, 2024  07:43:11
```
NOTE: cray cc apparently uses different options to get the version number (newer versions are based on clang, not sure about older crays):
```
OLD:

cc -V
Cray C : Version 8.7.0  Tue Jul 23, 2024  07:39:46

cc -V
Cray C : Version 8.5.7  Tue Jul 23, 2024  07:40:41
```
 
```
Newer CC:

cc -v
Cray clang version 15.0.1  (66f7391d6a03cf932f321b9f6b1d8612ef5f362c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/cray/pe/cce/15.0.1/cce-clang/x86_64/share/../bin
Found candidate GCC installation: /opt/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0
Selected GCC installation: /opt/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

2024-07-24 00:43 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +        version_string = '.'.join(str(x) for x in self.get_version())
I'll add this. At first I was worried that 'version string' might suggest the whole string returned from `--version`, but I'll change the comments to refer to that whole output as 'version output', and 'version string' will always mean just the semver string.

2024-07-26 07:11 UTC, lukehoffmann commented on tests/unit_tests/tools/test_compiler.py
>          with mock.patch.object(c, 'run', side_effect=FileNotFoundError()):
Interesting, I can't actually make it raise the FileNotFound error. If I put a bogus exec_name the in just raises a RuntimeError

2024-07-26 07:13 UTC, lukehoffmann commented on tests/unit_tests/tools/test_compiler.py
>          with mock.patch.object(c, 'run', side_effect=FileNotFoundError()):
Oh, that's because the FileNotFoundError is already handled in the tool.run() function. I don't need this test at all

2024-07-29 00:02 UTC, lukehoffmann commented on tests/unit_tests/tools/test_compiler.py
> +            cc.get_hash()
Done

2024-07-29 00:02 UTC, lukehoffmann commented on tests/unit_tests/tools/test_compiler.py
> +            cc.get_hash()
Done

2024-07-29 00:04 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +        version_string = '.'.join(str(x) for x in self.get_version())
I added a new `get_version_string()` function

2024-07-29 00:04 UTC, lukehoffmann commented on source/fab/tools/compiler.py
>      def get_version(self):
Done

2024-07-29 00:06 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +        if self.version_token not in res:
I did change the property to `compiler_identifier` in one commit, but now it is factored out and is just part of the pattern matching in `IntelCompiler` and `GnuCompiler`

2024-07-29 00:08 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +            version_string = res.split(')')[1].split()[0]
I've changed the design to use mixins for `IntelCompiler` and `GnuCompiler`, so we would eventually add `CrayCompiler` and `NvidiaCompiler` as required.

2024-07-29 00:14 UTC, lukehoffmann commented on tests/unit_tests/tools/test_compiler.py
>          assert not cc.check_available()
I prefer to only test one thing in each unit test, so if we want to test caching for `check_available` then I can add another unit test (or two).
I've added explicit caching tests for the `get_version` function (see `test_get_version_good_result_is_cached()` and `test_get_version_bad_result_is_not_cached()`. Do you think that covers the caching question here, since `check_available` is basically a wrapper for `get_version`?

2024-07-29 00:19 UTC, lukehoffmann commented on tests/unit_tests/tools/test_compiler.py
> +        # A change in the name must change the hash, again:
This caused an error after my changes, because it was actually calling the gnu compiler and getting the real output, but it was expecting it to say 'new_name' 😄

2024-07-29 01:44 UTC, lukehoffmann commented on tests/unit_tests/tools/test_compiler.py
> +def test_get_version_string():
I might have gone too far refactoring out your test class here. Let me know and I can add it back if you'd prefer.
My thinking was:
* It's good to be clear about which class we're actually testing in each test, because we're not actually testing the base `Compiler` class now, and
* I'd also prefer to have separate tests for the caching behaviour, and try to keep each test focussed on one thing

2024-07-29 01:47 UTC, lukehoffmann commented
@hiker , can you please look again and see if you're happy with the new changes?

I'm not sure if it will show up for you, but I made [this comment](https://github.com/hiker/fab_new/pull/9/files#r1694412977) about some changes I made to the testing.

2024-07-29 04:34 UTC, hiker commented on source/fab/tools/compiler.py
>      def get_version(self):
Thanks, I learned something, I had no idea that I was supposed to use `, ...`  :)

2024-07-29 04:34 UTC, hiker commented on source/fab/tools/compiler.py
> +            version_string = res.split(')')[1].split()[0]
Perfect.

2024-07-29 05:11 UTC, hiker requested changes
Great job, nearly done. I spotted two errors in tests I think (incorrect indentation), and I think we can remove some of the code duplication in the mixins. Otherwise it's a great job!

2024-07-29 05:11 UTC, hiker commented on tests/unit_tests/tools/test_compiler.py
>          assert not cc.check_available()
My bad, you are right - I missed them in the long list of compiler version lines :)

2024-07-29 05:11 UTC, hiker commented on source/fab/tools/compiler.py
> +class GnuCompiler(Compiler):
Since I need to give it back to you anyway, do you mind renaming the two mixing classes to have a better name (since they are not really compilers). E.g.: GnuVersioning and IntelVersioning? Or so (GnuVersionHandling, ...? Or GnuVersionMixin, ...? I am bad with names, pick anything :) )

2024-07-29 05:11 UTC, hiker commented on tests/unit_tests/tools/test_compiler.py
>          with mock.patch.object(c, 'run', side_effect=FileNotFoundError()):
Probably my fault, when refactoring the original code I probably lost track of what test is where. Thanks for following this up!

2024-07-29 06:36 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +class GnuCompiler(Compiler):
That's a good idea. I went with GnuVersionHandling

2024-07-29 06:46 UTC, lukehoffmann commented on source/fab/tools/compiler.py
> +    def _run_version_command(self) -> str:
That's a good way to do it, then we wouldn't even need to duplicate the error handling when overriding later.
I've moved it back to the base, with the optional command parameter you suggested.

2024-07-29 06:48 UTC, lukehoffmann commented
Good suggestions, thanks! I think that's all done now

2024-07-31 06:24 UTC, hiker requested changes

2024-07-31 06:26 UTC, hiker commented
One minor thing that I missed in the original review, my apologies. It caused me a lot of headache, and googling and reading :)

2024-08-02 01:54 UTC, lukehoffmann commented
Yeah I should have revisited that inheritance design, I wasn't really sure how I'd got it to work.

I tried just removing the Compiler inheritance from the mixins, and that worked but mypy didn't like it. Their documentation says to use a Protocol in that situation - I tried that and it didn't work in the python 3.7.

In the end I realised I wasn't really designing mixins. A mixin should add functionality, not try to override something in the main class. So decided to make the mixins very simple, with just static methods (so effectively no 'self') . The compiler classes are the ones who do the overrides, and then call into the mixins. See what you think. I think it's clearer to understand what's happening, even if it's more verbose.

2024-08-02 09:18 UTC, hiker commented
> I tried just removing the Compiler inheritance from the mixins, and that worked but mypy didn't like it. Their documentation says to use a Protocol in that situation - I tried that and it didn't work in the python 3.7.
Dang - I read somewhere that there is an additional package for 3.7, but that is all just ugly.

I wonder if we could have just use `cast` to make self a `Compiler`.
> 
> In the end I realised I wasn't really designing mixins. A mixin should add functionality, not try to override something in the main class. So decided to make the mixins very simple, with just static methods (so effectively no 'self') . The compiler classes are the ones who do the overrides, and then call into the mixins. See what you think. I think it's clearer to understand what's happening, even if it's more verbose.

Sounds good to me, thanks!

2024-08-02 09:18 UTC, hiker approved these changes
The current solution works fine, so thanks a lot

2024-08-02 09:23 UTC, merged

2024-08-02 09:24 UTC, hiker commented
Thanks a lot! Note that I did not delete the branch since we still need it to be merged into MetOffice's upstream Fab.

@jasonjunweilyu  - it might be great if one of you could update lfric_atm-fab - note that you can compare tuples with different number of elements, e.g. `(19,) < (19,5) < (19,10)` etc. That should simplify the existing version checks. And ask @lukehoffmann  for a review.

2024-08-06 00:37 UTC, jasonjunweilyu commented
> Thanks a lot! Note that I did not delete the branch since we still need it to be merged into MetOffice's upstream Fab.
> 
> @jasonjunweilyu - it might be great if one of you could update lfric_atm-fab - note that you can compare tuples with different number of elements, e.g. `(19,) < (19,5) < (19,10)` etc. That should simplify the existing version checks. And ask @lukehoffmann for a review.

@lukehoffmann 
I just tried using the updated `get_version` function in lfric_atm_fab, and I got this version output format unexpected error here when first loading ifort and switching to mpif90: https://git.nci.org.au/bom/ngm/lfric/lfric_atm-fab/-/jobs/74171#L88
Is this related to `def parse_intel_version_output` in `class IntelVersionHandling()` in `tools/compiler.py`?

2024-08-06 02:55 UTC, lukehoffmann commented
> I just tried using the updated `get_version` function in lfric_atm_fab, and I got this version output format unexpected error here when first loading ifort and switching to mpif90: https://git.nci.org.au/bom/ngm/lfric/lfric_atm-fab/-/jobs/74171#L88 Is this related to `def parse_intel_version_output` in `class IntelVersionHandling()` in `tools/compiler.py`?

```
Error getting compiler version: Unexpected version output format for compiler 'mpif90-intel-classic': ifort (IFORT) 2021.9.0 20230302
Copyright (C) 1985-2023 Intel Corporation.  All rights reserved.
```

Yes @jasonjunweilyu, that is the new code trying to enforce that the intel compiler is being used. Unfortunately it is expecting the wrong output because the `compiler.name` property is now `'mpif90-intel-classic'` instead of `'ifort'`.

Do you know where the name is being set? It might be that we have to revisit this change if it doesn't work with mpi.

2024-08-06 04:51 UTC, lukehoffmann commented
@hiker I think I do need to make some changes here. I shouldn't be relying on the `compiler.name` property because that will be changed in different implementations. I think it should just be checking against hardcoded strings depending on `compiler.category` (or maybe we don't need to actually check for c vs. fortran, is it enough to check for Intel vs. GNU?)

Should I make more changes in the same branch?

2024-08-06 13:42 UTC, hiker commented
No, don't change this for now. My current work replaces the compiler wrapper, so while it will still be called (say) mpif90-ifort (or mpif90-intel-classic), the compiler wrapper will forward the `get_version` to the actual compiler, which will have the right name.

The only problem I need to think about: I added a consistency test, that the version number of the wrapped compiler must be the same as the compiler wrapper (in case that say mpif90 is hard-coded to use a different intel compiler version) - I think I can get this to work by using the wrapper version output as input to the wrapper-compiler, but need to study the code bit.

Thanks

2024-08-07 01:14 UTC, hiker commented
I'll fix this up as part of my compiler wrapper change. I also noticed some unexpected behaviour with the regex:
```
exp = name + r" \(.*?\) (\d[\d\.]+\d)\b"
```
The version part of this regex matches `777`, but not `77`, which explains a coverage issue in the testing. You test for:
```
GNU Fortran (gcc) 77
```
and this does not match the regex, so the failure happens not in the expected part of the code where it is checked that a compiler version must be at least major.minor. Sorry, I totally missed that (usually I run coverage tests :(  )

Since I have already merged this into my branch (including the expected fair amount of conflicts), I think it's easier I'll fix this up in my branch (since I already have modified the tests heavily).

2024-08-07 06:30 UTC, hiker commented
@lukehoffmann, good suggestion to remove the compiler name, it looks a lot cleaner and short now (fwiw: https://github.com/hiker/fab_new/blob/540b544fe20170d30ea34cfe71fcf8e7bbe7f0a5/source/fab/tools/compiler.py#L329)

It also fixes the compiler name handling, and simplifies the version handling a bit.

2024-08-07 13:32 UTC, hiker commented
I've back-ported the changes to the version handling, so we avoid that this might come up in the code review.